name: Greetings

on:
  pull_request_target:
    types:
      - opened 

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Comment on PR
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo, number } = context.issue;
            const author = context.payload.sender.login; // Use 'sender.login' to get the PR author's login.
            const body = `Hello! 👋 Thank you @${author} for your pull request! \n We appreciate your contribution to "Frontend-Treasure" for Hacktoberfest. Your effort helps make our project better. 🌟 \nOur team will review your PR soon. In the meantime, feel free to explore more ways to contribute or join our community discussions. Your involvement is important to us! \n Keep up the great work! 🚀`;
            await context.github.issues.createComment({ owner, repo, issue_number: number, body: body });
            console.log(`Commented on PR of user @${author}`);
